# Generated by Django 2.1.2 on 2018-10-10 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.TextField(max_length=300)),
                ('longitude', models.TextField(max_length=300)),
                ('address', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=250)),
                ('imgpath', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_choice', models.IntegerField(choices=[(1, 'PHONE'), (2, 'FACEBOOK'), (3, 'EMAIL')])),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('desription', models.TextField(max_length=1500)),
                ('logo', models.TextField(max_length=1000)),
                ('branches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Branch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Category')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Contact')),
            ],
        ),
    ]
